In [61]:
import pandas as pd
import numpy as np
dataset=pd.read_csv("Social_Network_Ads.csv");
print(dataset)

X=dataset.iloc[:,2:4].values
#X=X.reshape(-1,1)
#print(X)
y=dataset.iloc[:,4].values
print(y)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0

In [62]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
print(X_train)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
from sklearn.linear_model import LogisticRegression
regressor=LogisticRegression()
regressor.fit(X_train,y_train)

[[    35  72000]
 [    33  41000]
 [    35  75000]
 [    47  51000]
 [    58 144000]
 [    24  55000]
 [    39  42000]
 [    18  68000]
 [    35 108000]
 [    38  61000]
 [    37  33000]
 [    33  43000]
 [    56  60000]
 [    56 133000]
 [    37 137000]
 [    26  80000]
 [    48  29000]
 [    25  33000]
 [    46  79000]
 [    35  60000]
 [    39  79000]
 [    40  65000]
 [    33 149000]
 [    45  22000]
 [    23  28000]
 [    35  44000]
 [    20  74000]
 [    38  61000]
 [    59 143000]
 [    28  32000]
 [    47  43000]
 [    31  68000]
 [    27  17000]
 [    31  18000]
 [    35  50000]
 [    29  61000]
 [    46  74000]
 [    55  39000]
 [    40  61000]
 [    27  54000]
 [    42 149000]
 [    31  34000]
 [    35  97000]
 [    40 142000]
 [    18  52000]
 [    22  55000]
 [    39 122000]
 [    40  59000]
 [    48 134000]
 [    21  68000]
 [    52 114000]
 [    29 148000]
 [    31  89000]
 [    53  72000]
 [    35 147000]
 [    49  28000]
 [    41  72000]
 [    36 118000]
 [    18  8200

LogisticRegression()

In [63]:
y_pred=regressor.predict(X_test)
print(y_pred)
print(y_test)
print(X_test)

[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0
 1 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 1 0 0 1
 0 0 0 0 1 0]
[1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0
 1 0 0 0 0 1 1 1 0 0 1 0 1 0 0 1 1 0 0 1 0 0 1 0 0 1 0 1 1 1 0 0 1 0 1 1 1
 0 1 0 0 1 0]
[[ 0.70230623 -1.28748211]
 [-0.05630303  0.121246  ]
 [-0.15112919  0.1505945 ]
 [-1.00456461  0.41473102]
 [-0.72008614  0.29733701]
 [-0.15112919 -1.08204259]
 [-0.72008614 -0.61246656]
 [-0.8149123   0.1505945 ]
 [ 1.27126318  1.88215614]
 [-0.15112919  0.85495856]
 [ 0.70230623 -0.72986057]
 [ 0.98678471 -1.1700881 ]
 [-1.09939077  1.4125801 ]
 [-0.24595535  0.20929151]
 [ 0.3230016   0.29733701]
 [ 0.79713239  0.76691305]
 [-1.00456461 -0.34833004]
 [-0.53043382  0.88430706]
 [-0.24595535 -1.46357312]
 [-0.05630303 -0.37767854]
 [ 2.02987245  1.76476213]
 [ 1.17643703 -0.99399709]
 [ 0.89195855 -0.58311805]
 [-0.34078151  0.062549  ]
 [-1.00456461 -1.4635731

In [64]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred) 
print(cm)

[[45  5]
 [16 14]]
