In [8]:
import numpy as np
import pandas

#we have to change all input and output in number


dataset=pandas.read_csv("FirstDataset.csv")
print(dataset)
#dataset=dataset.dropna()
#X=dataset.iloc[0:9,0:3]#iloc means index location

X=dataset.iloc[:,0:3].values# converted into list
Y=dataset.iloc[:,3].values

#print(X)
#print(Y)

from sklearn.impute import SimpleImputer

## taking mean
imputer=SimpleImputer(missing_values=np.nan,strategy="median") # we can use most_frequent or median or mean
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])
print(X)



#label encoder convert all numeric data
from sklearn.preprocessing import LabelEncoder
labelEncoder=LabelEncoder()
"""X[:,0]=labelEncoder.fit_transform(X[:,0]) #transform and best fit the data  #we fit the data and transform in a single method and use different in other line

# X[:,0]=LabelEncoder().fit((X[:,0]).transform(X[:,0]) another method

print(X)
"""

#we dont use same tarnsformation for x and y because it will give same number is yes is written in both input and output
labelEncoderOutput=LabelEncoder()
labelEncoderOutput.fit(Y) #it gives number to all label  #first use fit the data
Y=labelEncoderOutput.transform(Y)#and then transform the data
print(Y)

#removing priorty to the column so that out data can get in accurate



from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[0])],remainder="passthrough")
X=np.array(ct.fit_transform(X))
print(X)


"""
from sklearn.preprocessing import StandardScaler#it scales the value between -3 to3
norm=StandardScaler()
X=norm.fit_transform(X)
print(X)
"""

from sklearn.preprocessing import MinMaxScaler #it scales value between 0 and 1
norm=MinMaxScaler()
X=norm.fit_transform(X)
print(X)



  Location   Age   Salary Bonus Offered
0    Delhi  44.0  72000.0            No
1   Mumbai  27.0  48000.0           Yes
2   Mumbai  30.0  54000.0            No
3    Delhi  38.0  61000.0            No
4  Chennai  40.0      NaN           Yes
5   Mumbai  35.0  58000.0           Yes
6  Chennai   NaN  52000.0            No
7   Mumbai  48.0  79000.0           Yes
8    Delhi  50.0  83000.0            No
9   Mumbai  37.0  67000.0           Yes
[['Delhi' 44.0 72000.0]
 ['Mumbai' 27.0 48000.0]
 ['Mumbai' 30.0 54000.0]
 ['Delhi' 38.0 61000.0]
 ['Chennai' 40.0 61000.0]
 ['Mumbai' 35.0 58000.0]
 ['Chennai' 38.0 52000.0]
 ['Mumbai' 48.0 79000.0]
 ['Delhi' 50.0 83000.0]
 ['Mumbai' 37.0 67000.0]]
[0 1 0 0 1 1 0 1 0 1]
[[0.0 1.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 30.0 54000.0]
 [0.0 1.0 0.0 38.0 61000.0]
 [1.0 0.0 0.0 40.0 61000.0]
 [0.0 0.0 1.0 35.0 58000.0]
 [1.0 0.0 0.0 38.0 52000.0]
 [0.0 0.0 1.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 37.0 67000.0]]
[[0.   

In [ ]:
from sklearn.linear_model import LinearRegression

predictor = LinearRegression(n_jobs=-1)
predictor.fit(X=TRAIN_INPUT, Y=TRAIN_OUTPUT)
predictor